[PHP] Inline rotatePHPRuntime() into the PHP class (#2559)
## Motivation for the change, related issues

Moves the `rotatePHPRuntime()` logic inside the PHP class and properly
await them to prevent async rotation failures:

```
{
  type: 'request.error',
  error: Error: PHP.run() failed with exit code 255.
      at runExecutionFunction.then.dispatchEvent.type (/Users/cloudnik/www/Automattic/core/plugins/wordpress-playground/packages/php-wasm/universal/src/lib/php.ts:1052:14),
  source: 'php-wasm'
}
Trace: hotSwapPHPRuntime called on a disposed PHP instance
    at PHP.hotSwapPHPRuntime (/Users/cloudnik/www/Automattic/core/plugins/wordpress-playground/packages/php-wasm/universal/src/lib/php.ts:1272:13)
    at rotateRuntime (/Users/cloudnik/www/Automattic/core/plugins/wordpress-playground/packages/php-wasm/universal/src/lib/rotate-php-runtime.ts:45:14)
    at async rotateRuntimeForPhpWasmError (/Users/cloudnik/www/Automattic/core/plugins/wordpress-playground/packages/php-wasm/universal/src/lib/rotate-php-runtime.ts:64:4)
```

## Implementation

The `rotatePHPRuntime()` function kills the "worn out" PHP Emscripten
runtimes and replaces them with new ones. php-fpm does the same thing.
Rotating the runtime happens in response to a few events emitted by the
PHP class. However, rotation is an async operation and event listeners
are expected to be synchronous. As a result, a PHP instance may get
killed and the rotate handler will attempt to rotate it asynchronously,
causing errors such as the one cited above.

This PR inlines that logic in the PHP class via a new
`php.enableRuntimeRotation()` method. The PHP instance now keeps track
if the rotation condition internally and optionally rotates the runtime
before every `php.run()`, `php.runStream()`, and `php.cli()` call. This
approach also has other benefits:

* Ability to call `php.cli()` and `php.run()` multiple times without
trashing the instance – the rotation is handled internally.
* It creates a way to get rid of the `primary` and `secondary` PHP
instance concept in the PHPProcessManager class. We no longer need to
worry about accidentally trashing the primary instance by calling
`.cli()` on it.
* The rotation is now lazy, not eager, and only happens on the next PHP
code execution.

### Potential follow-up work

* Expose a static `PHP.create( runtimeFactory )` method to simplify the
instance constructions. Right now you need to do `const php = new PHP(
runtimeId ); PHP.enableRuntimeRotation( runtimeFactory );`.

## Testing Instructions (or ideally a Blueprint)

CI

---------

Co-authored-by: Brandon Payton <brandon@happycode.net>